workspace "Forge v2" "Bottom-up C4 model of forge — an idea machine that runs six phases (backed by a three-scope brain) primarily unattended for one human across many side projects. Generated by the c4-architecture skill (Structurizr DSL) from a ground-truth code read on 2026-05-30." {

    !identifiers flat
    !impliedRelationships true

    model {

        // ---------------------------------------------------------------
        // People
        // ---------------------------------------------------------------
        operator = person "Operator" "The single human running forge across side projects. Touches the system at exactly three points, all on the forge UI (ADR 023): architect (idea -> initiative), review (approve the cycle), reflection (feedback)."

        // ---------------------------------------------------------------
        // External systems
        // ---------------------------------------------------------------
        claudeSdk    = softwareSystem "Claude Agent SDK" "Anthropic's agent runtime + harness (model calls, tool use, prompt caching). Every forge agent runs here; forge hosts no model runtime, vector DB, or harness of its own." "External"
        github       = softwareSystem "GitHub" "Hosts the managed-project repos. The PR is the operator's sole review + merge surface; merge state is the single terminal signal." "External"
        projectRepo  = softwareSystem "Managed Project Repo" "A side-project git repo forge develops (trafficGame, terraform-provider-betterado, claude-harness...). Has its own quality gate and its own Brain 3. Worktrees branch from it." "External"
        graphify     = softwareSystem "graphify (CLI)" "External tree-sitter knowledge-graph tool. Rebuilds the three brain graphs, triggered by a post-commit hook." "External"
        obsidian     = softwareSystem "Obsidian" "Renders the brain as a navigable vault so the human reads the same graph the agents query." "External"

        // ---------------------------------------------------------------
        // The system under design
        // ---------------------------------------------------------------
        forge = softwareSystem "Forge v2" "Six phases backed by a brain; designed to run primarily unattended between three human interaction points." {

            // === Container: the forge engine (the `forge serve` Node process) ===
            engine = container "Orchestrator Engine" "The hot path: a persistent scheduler that claims initiatives and runs them through five in-cycle phases, isolated per git worktree, recoverable by heartbeat. Caps its own surface area by design (ADRs 011-013)." "TypeScript / Node (forge serve)" {

                // -- scheduler tier (unattended loop) --
                sched         = component "Scheduler" "~150-line forever loop: claims pending initiatives, spawns each in a worktree, heartbeats, recovers orphans, notifies." "scheduler.ts" "Scheduler"
                schedDispatch = component "Scheduler Dispatch" "Routes a finished cycle's terminal status: done / failed / bounded auto-retry back to pending." "scheduler-dispatch.ts" "Scheduler"
                daemon        = component "Daemon Control" "Detached `forge serve` process state: pid, pause/resume flag, serve.log." "daemon.ts" "Scheduler"

                // -- cycle spine + the five phases --
                cycleSpine   = component "Cycle Runner (spine)" "Thin orchestration: threads phase outputs into the next phase, emits start/end events, classifies failures, snapshots artifacts. Resumable from the unifier (ADR 019)." "cycle.ts"
                pmPhase      = component "PM Phase" "Phase 1: invoke project-manager to decompose the initiative into atomic, dependency-ordered work items." "phases/project-manager.ts" "Phase"
                devPhase     = component "Dev-Loop Phase" "Phase 2: walk the WI DAG topologically, run a Ralph loop per work item, then the unifier (final Ralph) for cross-WI proof + demo + PR body." "phases/developer-loop.ts" "Phase"
                reviewPhase  = component "Review Phase" "Phase 3: open the demo-embedded PR (thin, non-LLM); the PR is the operator's surface. Never merges." "phases/reviewer.ts" "Phase"
                closurePhase = component "Closure Phase" "Phase 4: the single terminal-move authority. Confirms the merge (gh pr view), aligns local->remote, moves the manifest to done/." "phases/closure.ts" "Phase"
                reflectPhase = component "Reflection Phase" "Phase 5 (post-merge only): one-shot reflector that digests the event log and writes brain themes." "phases/reflector.ts" "Phase"

                // -- shared engine machinery --
                ralphRt        = component "Ralph Loop Runtime" "Swappable agentic loop: re-read PROMPT/AGENT/fix_plan -> SDK query() -> commit -> check stop conditions (gate pass | iteration/cost budget). loops/_adapters is the placeholder for alternatives." "loops/ralph/"
                invContracts   = component "Invocation Contracts" "Single source of truth for each phase's system+user prompt, model, and allowed/disallowed tools." "*-invocation.ts"
                queueApi       = component "Queue State Machine" "Atomic manifest transitions via rename(); manifest + work-item parse/validate/topo-sort." "queue.ts / manifest.ts / work-item.ts"
                worktreeMgr    = component "Worktree Manager" "Thin wrapper over git worktree add/remove/prune; self-heals stale registry state." "worktree.ts"
                prAdapter      = component "PR / Git Adapter" "The only place forge shells git push / gh pr; enforces the local<->remote sync invariant; shims gh locally for no-origin projects." "pr.ts (+ gh-shim.ts)"
                verdictProvider = component "Verdict Parser" "Resolves the operator's review verdict from the verdict file the UI bridge writes (ADR 023 — the PR-comment provider + getVerdict seam were retired)." "file-verdict.ts"
                eventLogger    = component "Event Logger" "Append-only JSONL event log + tool-use telemetry. The single source of truth for a cycle." "logging.ts / tool-event-emit.ts"
                failClassifier = component "Failure Classifier" "Reads the event log post-mortem; infers failure mode + recoverability; writes the human-facing REPORT.md." "failure-classifier.ts / cycle-report.ts"
                notifier       = component "Notifier" "Best-effort desktop + webhook notifications on terminal events." "notify.ts"
                architectRunner = component "Architect Runner (in-UI)" "Turn-based, file-checkpointed architect driven from the UI bridge (ADR 020); advances one step per call via the LLM council." "architect-runner.ts"
                engineConfig   = component "Config" "Per-machine forge.config.json + per-project .forge/project.json (quality gate, demo shape, heartbeat)." "config.ts / project-config.ts"
            }

            // === Container: the skill catalog (the agent surface) ===
            skills = container "Phase & Brain Skills" "The Claude Code skill catalog - forge's agent surface. Each skill is a system prompt + tool policy the engine loads into an SDK query(). Brain skills are the brain's read/write API." "Claude Code skills" {
                skPm         = component "project-manager" "Decompose an initiative into atomic work items with given-when-then ACs and explicit dependencies." "skills/project-manager" "Skill"
                skDev        = component "developer-ralph" "Drive a single work item to green via the Ralph loop." "skills/developer-ralph" "Skill"
                skUnifier    = component "developer-unifier" "Prove cross-WI acceptance, author the structured demo + PR body." "skills/developer-unifier" "Skill"
                skReflect    = component "reflector" "Post-merge retrospective: read the event log + merged tree, write brain themes + cycle archive." "skills/reflector" "Skill"
                skArchitect  = component "architect (+ llm-council)" "Turn ideas + roadmap + brain into an initiative via a CEO/eng/design/DX council that escalates only taste decisions." "skills/architect, skills/architect-llm-council" "Skill"
                skDemo       = component "demo / demo-capture" "Author a Playwright before/after behavioural demo; backfill screenshots when the change is visual." "skills/demo, skills/demo-capture" "Skill"
                skBrainQuery = component "brain-query" "Read the brain (graph-first, then keyword). Mandated first action of every planner + the reflector; logs gaps." "skills/brain-query" "Skill"
                skBrainIngest = component "brain-ingest" "The only writer: append _raw sources, create/update theme pages, sync category indexes." "skills/brain-ingest" "Skill"
                skBrainLint  = component "brain-lint" "Structural integrity checks over the brain (frontmatter, index-sync, staleness, orphans, length)." "skills/brain-lint" "Skill"
                skBrainGraph = component "brain-graph" "Maintain the three structural graphs by wrapping the graphify CLI." "skills/brain-graph" "Skill"
            }

            // === Container: operator CLI utilities ===
            cli = container "CLI Utilities" "forge subcommands (serve / watch / status / metrics / brain / requeue). The human moments are NOT here — they run on the UI (ADR 023)." "TypeScript (bin/forge.mjs)" {
                cliCore     = component "forge subcommands" "serve, status, metrics, requeue, preflight, brain index/lint." "orchestrator/cli.ts, cli/*.ts"
                cliWatch    = component "forge watch" "Launches the UI bridge + the Next.js dev server on fixed ports and opens the browser." "cli/forge-watch.ts"
                cliArchPlan = component "architect plan render" "Renders the in-UI architect session state -> PLAN.md + zero-dep PLAN.html (read on the /architect plan gate)." "cli/architect-plan.ts"
                cliDemo     = component "demo bundle builder" "Materialises before/after worktrees, runs the demo spec, composes the self-contained comparison bundle." "cli/demo*.ts"
            }

            // === Container: the UI bridge ===
            uiBridge = container "UI Bridge" "WebSocket + HTTP server (:4123). Tails the event log and scans the queue, streams snapshots + events to the browser, and accepts verdict/feedback files. Stateless: re-derives everything from the stores." "TypeScript (ws)" "Bridge"

            // === Container: the operator dashboard ===
            forgeUi = container "forge-ui Dashboard" "Next.js operator UI (:4124): the cascading hex pipeline, the grouped initiative pane, and the dedicated architect / review / reflect screens. Every load-bearing state is mirrored to data-* attributes (DOM-as-metrics)." "Next.js / React"

            // === Container: the monitor ===
            monitor = container "Monitor" "tmux 3-pane layout (serve stdout / live event tail / forge status --watch) plus an Obsidian vault launcher." "Shell / tmux"

            // === Data stores ===
            queueStore = container "Initiative Queue" "Filesystem state machine of initiative manifests: pending -> in-flight -> ready-for-review -> done | failed. Atomic rename transitions; heartbeat files enable crash recovery. done/ implies MERGED." "Filesystem (_queue/)" "Store"
            eventStore = container "Event Log + Artifacts" "Append-only per-cycle JSONL event log plus snapshotted work-items / demo / REPORT.md. The replayable source of truth for reflection, the UI, and metrics." "Filesystem (_logs/)" "Store"

            brainStore = container "Brain (three knowledge graphs)" "A Karpathy-style LLM wiki rendered as an Obsidian vault, in three scopes. Each scope has _raw/ (immutable), themes/ (~15-60 line pages), category indexes, and a graphify graph." "Markdown + graphify graphs" "Store" {
                brain1 = component "Brain 1 - forge-dev" "Forge engineering knowledge: TypeScript source + ADRs + decision/reference themes (~3,375 nodes). Read by forge-dev sessions, not by the cycle." "brain/forge-dev/" "Store"
                brain2 = component "Brain 2 - cycles" "Cross-cycle patterns / antipatterns + immutable cycle archives (~519 nodes). Read by planners + reflector." "brain/cycles/" "Store"
                brain3 = component "Brain 3 - per-project" "Whole-project knowledge (code + themes), living INSIDE each managed project's repo. Read by every cycle phase." "projects/<name>/brain/" "Store"
            }
        }

        // ---------------------------------------------------------------
        // Relationships - Operator
        // ---------------------------------------------------------------
        operator -> cli "Runs forge serve / watch / status / metrics in" "terminal"
        operator -> forgeUi "Drives all three human moments + watches cycles on" "browser"
        operator -> github "Reviews + merges the PR in" "browser"
        operator -> monitor "Tails live progress via" "tmux"
        operator -> obsidian "Browses the brain via"

        // ---------------------------------------------------------------
        // Relationships - CLI
        // ---------------------------------------------------------------
        cliCore -> sched "Starts the scheduler (forge serve)"
        cliCore -> queueStore "Requeue / promote manifests"
        cliCore -> eventStore "Reads for metrics / status / recap"
        cliCore -> brainStore "brain index / lint"
        cliWatch -> uiBridge "Launches"
        cliWatch -> forgeUi "Launches (Next.js dev server)"
        cliArchPlan -> queueStore "Renders PLAN from the architect session state"
        cliDemo -> projectRepo "Builds before/after worktrees + runs Playwright"

        // ---------------------------------------------------------------
        // Relationships - UI
        // ---------------------------------------------------------------
        forgeUi -> uiBridge "Subscribes to snapshots + events; posts verdicts" "WebSocket/HTTP :4123"
        uiBridge -> eventStore "Tails the event log (200ms)"
        uiBridge -> queueStore "Scans manifests; writes verdict files"
        uiBridge -> architectRunner "Drives the in-UI architect runner + scheduler controls"

        // ---------------------------------------------------------------
        // Relationships - Scheduler tier
        // ---------------------------------------------------------------
        sched -> queueStore "Claims + recovers manifests (atomic rename) + heartbeats"
        sched -> worktreeMgr "Adds a worktree per claimed initiative"
        sched -> cycleSpine "Runs a cycle per claimed initiative"
        sched -> schedDispatch "Routes terminal status via"
        sched -> notifier "Surfaces completion via"
        sched -> daemon "Honors pause/resume + pid via"
        schedDispatch -> queueStore "Moves the manifest (done / failed / pending)"
        worktreeMgr -> projectRepo "git worktree add / remove" "git"

        // ---------------------------------------------------------------
        // Relationships - Cycle spine -> phases
        // ---------------------------------------------------------------
        cycleSpine -> pmPhase "1. decompose"
        cycleSpine -> devPhase "2. build"
        cycleSpine -> reviewPhase "3. open PR"
        cycleSpine -> closurePhase "4. confirm merge + align"
        cycleSpine -> reflectPhase "5. reflect (only if merged)"
        cycleSpine -> eventLogger "Emits start/end + phase events to"
        cycleSpine -> failClassifier "Classifies failures + writes the report via"
        cycleSpine -> engineConfig "Reads forge.config / project.json via"

        // ---------------------------------------------------------------
        // Relationships - Phases -> skills / machinery
        // ---------------------------------------------------------------
        pmPhase -> invContracts "Builds the PM prompt via"
        pmPhase -> skPm "Invokes (one-shot) via SDK"
        devPhase -> invContracts "Builds the dev/unifier prompts via"
        devPhase -> ralphRt "Drives per-WI loops + the unifier via"
        ralphRt -> skDev "Runs each work-item iteration"
        ralphRt -> skUnifier "Runs the final unify + demo iteration"
        ralphRt -> claudeSdk "Calls query() each iteration (loads the dev/unifier skill)"
        ralphRt -> projectRepo "Commits worktree changes + runs the project quality gate" "git / shell"
        ralphRt -> eventLogger "Emits per-iteration cost + tool events to"
        reviewPhase -> prAdapter "Opens the demo-embedded PR via"
        reviewPhase -> verdictProvider "Reads the operator verdict via"
        closurePhase -> prAdapter "Confirms merge + aligns local->remote via"
        closurePhase -> queueStore "Moves the manifest to done / ready-for-review"
        reflectPhase -> invContracts "Builds the reflector prompt via"
        reflectPhase -> skReflect "Invokes (one-shot, post-merge) via SDK"
        architectRunner -> skArchitect "Advances the council one step via SDK"
        architectRunner -> queueStore "Writes the draft initiative + PLAN to the session"

        // ---------------------------------------------------------------
        // Relationships - Adapters -> externals / stores
        // ---------------------------------------------------------------
        prAdapter -> github "gh pr create / view; git push / fetch / ff" "gh / git"
        prAdapter -> projectRepo "Pushes the initiative branch to" "git"
        verdictProvider -> queueStore "Reads the UI-bridge-written verdict file in"
        eventLogger -> eventStore "Appends JSONL + snapshots to"
        failClassifier -> eventStore "Reads the event log; writes REPORT.md to"
        notifier -> operator "Notifies (desktop / webhook)"

        // ---------------------------------------------------------------
        // Relationships - Skills (brain-first + SDK + brain I/O)
        // ---------------------------------------------------------------
        skPm -> skBrainQuery "Queries the brain first (Brain 2 + 3)"
        skArchitect -> skBrainQuery "Queries the brain first (Brain 2 + 3)"
        skReflect -> skBrainQuery "Queries the brain (all three)"
        skDev -> skBrainQuery "May consult Brain 3 (advisory)"
        skReflect -> skBrainIngest "Writes new themes + cycle archive via"
        skBrainQuery -> brainStore "Reads themes + graphify graphs from"
        skBrainIngest -> brainStore "Appends _raw + themes + indexes to"
        skBrainLint -> brainStore "Checks structural integrity of"
        skBrainGraph -> brainStore "Rebuilds the knowledge graphs in"
        skBrainGraph -> graphify "Wraps"
        skPm -> claudeSdk "Executes on"
        skDev -> claudeSdk "Executes on"
        skUnifier -> claudeSdk "Executes on"
        skReflect -> claudeSdk "Executes on"
        skArchitect -> claudeSdk "Executes on"
        skDemo -> claudeSdk "Executes on"
        skReflect -> eventStore "Digests the event log in"
        skUnifier -> projectRepo "Writes the demo bundle + PR description to the worktree"
        skDemo -> projectRepo "Builds before/after + runs Playwright against"

        // ---------------------------------------------------------------
        // Relationships - external upkeep of the brain
        // ---------------------------------------------------------------
        graphify -> brainStore "Rebuilds the three graphs (post-commit hook)"
        obsidian -> brainStore "Renders as a vault"
        projectRepo -> github "Has its remote on / PRs opened against"

        // ---------------------------------------------------------------
        // Relationships - Monitor
        // ---------------------------------------------------------------
        monitor -> eventStore "Tails the event log in"
        monitor -> queueStore "Shows queue status from"
        monitor -> sched "Runs forge serve / status against"

        // ===============================================================
        // Deployment - single WSL2 workstation + cloud services
        // ===============================================================
        deploymentEnvironment "Local (WSL2)" {
            deploymentNode "Operator Workstation" "WSL2 on Windows" "Linux" {
                deploymentNode "Node.js runtime" "the forge serve process + CLI" "Node 22" {
                    containerInstance engine
                    containerInstance cli
                    containerInstance uiBridge
                    containerInstance skills
                }
                deploymentNode "Next.js dev server" "operator dashboard" "Next.js :4124" {
                    containerInstance forgeUi
                }
                deploymentNode "tmux" "live operator view" "tmux" {
                    containerInstance monitor
                }
                deploymentNode "Working tree" "the forge repo + projects/" "ext4" {
                    containerInstance queueStore
                    containerInstance eventStore
                    containerInstance brainStore
                    softwareSystemInstance projectRepo
                }
            }
            deploymentNode "Anthropic" "api.anthropic.com" "Cloud" {
                softwareSystemInstance claudeSdk
            }
            deploymentNode "GitHub" "github.com" "Cloud" {
                softwareSystemInstance github
            }
        }
    }

    // ===================================================================
    // Views
    // ===================================================================
    views {

        systemLandscape "Landscape" "Everything in one frame: the operator, forge, and the external services it leans on." {
            include *
            autoLayout lr
        }

        systemContext forge "Context" "Forge in its world: one operator, the Agent SDK that runs every agent, GitHub as the merge surface, the managed repos it builds, and the tools that render/index the brain." {
            include *
            autoLayout
        }

        container forge "Containers" "Inside forge: the orchestrator engine (hot path), the skill catalog it runs on the SDK, the CLI + UI + monitor surfaces, and the three filesystem stores (queue, event log, brain)." {
            include *
            autoLayout
        }

        component engine "EngineComponents" "Inside the orchestrator engine: the scheduler tier, the cycle spine + five phases, the Ralph runtime, and the shared machinery (queue, worktree, PR adapter, verdict, logging, classification)." {
            include *
            autoLayout
        }

        component skills "SkillCatalog" "The agent surface: the phase skills + the brain skills, every one of which runs on the Agent SDK and (for planners + reflector) queries the brain first." {
            include *
            autoLayout
        }

        component brainStore "BrainComponents" "The three-scope brain: forge-dev, cycles, and the per-project brain that lives inside each managed repo." {
            include *
            autoLayout
        }

        deployment forge "Local (WSL2)" "LocalDeployment" "How it actually runs today: one WSL2 workstation hosting the Node process, the Next.js UI, tmux, and the working tree; with Anthropic + GitHub in the cloud." {
            include *
            autoLayout
        }

        dynamic forge "UnattendedCycle" "The end-to-end flow from idea to merged PR, with the three human moments called out (all on the forge UI, ADR 023)." {
            operator -> forgeUi "1. Operator drives the in-UI architect; on approve its finalize writes the manifest to pending/"
            engine -> queueStore "2. Scheduler claims it (atomic rename to in-flight)"
            engine -> projectRepo "3. Spawns a git worktree from the project repo"
            engine -> skills "4. PM decomposes into work items"
            skills -> claudeSdk "5. Agents run on the SDK"
            engine -> projectRepo "6. Ralph + unifier build, commit, run the quality gate"
            engine -> github "7. Review phase opens the demo-embedded PR"
            operator -> forgeUi "8. Operator approves the cycle on the /review screen (the PR is still the merge boundary)"
            engine -> github "9. Closure confirms the merge"
            engine -> queueStore "10. Closure moves the manifest to done/"
            engine -> skills "11. Reflection digests the event log"
            skills -> brainStore "12. brain-ingest writes new themes + the cycle archive"
            autoLayout
        }

        dynamic engine "DevLoopIteration" "One developer-loop iteration: read institutional memory, call the model, commit, gate, repeat - until the gate passes or the budget is hit." {
            devPhase -> ralphRt "1. Walk the WI DAG; start a Ralph per work item"
            ralphRt -> claudeSdk "2. Read PROMPT/AGENT/fix_plan -> query()"
            ralphRt -> projectRepo "3. Commit changes + run the quality gate"
            ralphRt -> eventLogger "4. Emit iteration cost + tool events"
            ralphRt -> projectRepo "5. Repeat until gate passes; then the unifier writes the demo + PR"
            autoLayout
        }

        dynamic forge "KnowledgeFlow" "How forge learns cycle-over-cycle: reflection -> brain -> graph -> queryable next cycle." {
            skills -> brainStore "1. Reflector ingests themes + the cycle archive"
            graphify -> brainStore "2. Post-commit hook rebuilds the three graphs"
            skills -> brainStore "3. Next cycle: brain-query reads the graph + themes"
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
            element "Store" {
                shape Cylinder
                background #2f6f9f
                color #ffffff
            }
            element "Bridge" {
                shape Pipe
                background #438dd5
                color #ffffff
            }
            element "Skill" {
                shape Hexagon
                background #62548a
                color #ffffff
            }
            element "Phase" {
                background #f29b30
                color #000000
            }
            element "Scheduler" {
                background #5fa45f
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            relationship "Relationship" {
                routing Orthogonal
            }
        }
    }
}
